### ISSUE TITLE
kernel wishlist: rebuild with android13-5.10, renew x86_64 defconfig with gki_defconfig

### ISSUE THREAD

**Issue by busylog** [BlissRoms-x86/kernel_common#5]
https://android.googlesource.com/kernel/common/+/refs/heads/android13-5.10/arch/x86/configs/gki_defconfig

mglru is backported to android13-5.10, CONFIG_LRU_GEN=y
CONFIG_ZRAM=y is wishlist, need fstab & init.rc fixes to create swap.

**Comment by hmtheboy154** [comment]
For BlissOS 14.10 and future buids, we will use Kernel 5.15 instead, based on the `android13-5.15-lts` branch
https://github.com/hmtheboy154/Darkmatter-kernel/tree/umbral

I will consider ZRAM later but I already turn mgLRU on in this kernel
https://github.com/supremegamers/device_generic_common/blob/841cd34bb4aa22f2df87c17d351e3ddc6c7a3156/init.sh#L64
